import { OrganizationRole } from "../../../generated/prisma/enums";
import { Permission, Permissions } from "./permissions";

export const RolePermissions: Record<OrganizationRole, Permission[]> = {
  [OrganizationRole.OWNER]: Object.values(Permissions),
  [OrganizationRole.ORG_ADMIN]: Object.values(Permissions),
  [OrganizationRole.PROJECT_MANAGER]: [
    Permissions.ORG_READ,
    Permissions.MEMBER_READ,
    Permissions.TEAM_CREATE,
    Permissions.TEAM_READ,
    Permissions.TEAM_UPDATE,
    Permissions.TEAM_DELETE,
    Permissions.PROJECT_CREATE,
    Permissions.PROJECT_READ,
    Permissions.PROJECT_UPDATE,
    Permissions.PROJECT_ARCHIVE,
    Permissions.SPRINT_CREATE,
    Permissions.SPRINT_READ,
    Permissions.SPRINT_UPDATE,
    Permissions.TASK_CREATE,
    Permissions.TASK_READ,
    Permissions.TASK_UPDATE,
    Permissions.TASK_DELETE,
    Permissions.TASK_ASSIGN,
    Permissions.COMMENT_CREATE,
    Permissions.COMMENT_UPDATE,
    Permissions.COMMENT_DELETE,
    Permissions.ACTIVITY_READ,
    Permissions.BILLING_READ, // Can view billing but not manage
  ],
  [OrganizationRole.TEAM_LEAD]: [
    Permissions.ORG_READ,
    Permissions.MEMBER_READ,
    Permissions.TEAM_READ,
    Permissions.TEAM_UPDATE,
    Permissions.PROJECT_READ,
    Permissions.SPRINT_CREATE,
    Permissions.SPRINT_READ,
    Permissions.SPRINT_UPDATE,
    Permissions.TASK_CREATE,
    Permissions.TASK_READ,
    Permissions.TASK_UPDATE,
    Permissions.TASK_DELETE,
    Permissions.TASK_ASSIGN,
    Permissions.COMMENT_CREATE,
    Permissions.COMMENT_UPDATE,
    Permissions.COMMENT_DELETE,
    Permissions.ACTIVITY_READ,
  ],
  [OrganizationRole.MEMBER]: [
    Permissions.ORG_READ,
    Permissions.MEMBER_READ,
    Permissions.TEAM_READ,
    Permissions.PROJECT_READ,
    Permissions.SPRINT_READ,
    Permissions.TASK_CREATE,
    Permissions.TASK_READ,
    Permissions.TASK_UPDATE, // Own tasks mostly, handled in logic if needed
    Permissions.COMMENT_CREATE,
    Permissions.COMMENT_UPDATE,
    Permissions.COMMENT_DELETE,
    Permissions.ACTIVITY_READ,
  ],
  [OrganizationRole.GUEST]: [
    Permissions.ORG_READ,
    Permissions.PROJECT_READ,
    Permissions.SPRINT_READ,
    Permissions.TASK_READ,
    Permissions.COMMENT_CREATE,
  ]
};
